- src/app/_components/view/Page/index.module.scss
- src/app/_components/view/Page/index.tsx
- src/app/globals.scss
- src/app/page.tsx
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/1
- "クソコードは芸術なり"の文章を追加した。
- 鑑賞する・出展する・評価をみるのボタンを追加し、aタグのcssを追加した
> feat:トップページ完成

- .eslintrc.json
- src/app/(use-header)/layout.tsx
- src/app/_components/Header/index.module.scss
- src/app/_components/Header/index.tsx
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/6
- クソコード博覧会の文字を追加
- 鑑賞する・出展する・評価をみるボタンの追加
- css(文字サイズ、線)の追加
- ボタンホバー時のアニメーションの追加
> feat: headerの完成

- src/app/_components/Header/index.tsx
- src/app/_components/view/Page/index.tsx
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/13
aタグをLinkタグに置き換え
> refactor: aタグをLinkタグに置き換え

- src/app/layout.tsx
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/7
フォントを Sawarabi Mincho に変更
太さ1つしかないんだね
> change: フォントを変更

- src/app/(use-header)/post/_components/view/Page/index.module.scss
- src/app/(use-header)/post/_components/view/Page/index.tsx
- src/app/(use-header)/post/page.tsx
- 入力フォームの追加
- css(要素の幅や隙間)の追加
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/5
> feat:出展画面の完成

- src/app/(use-header)/post/_components/view/Page/index.tsx
- src/types/post.ts
- src/types/supabase.ts
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/21
> feat: 型の生成

- src/types/post.ts
- supabase/migrations/20240930042116_delete-tag-intermediate-table.sql
> タグの中間テーブルを削除

- src/stores/postAtom.ts
- src/stores/userAtom.ts
- src/types/post.ts
- src/types/supabase.ts
- supabase/seed.sql
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/8
supabase から post を取得する処理を追加した
なし
supabase にアクセスして情報を取得して、`src/types/post.ts` の Post[] の型で渡します
> feat: supabase から post を取得する処理

- src/stores/langAtom.ts
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/29
- lang 一覧をfetachしてくる
なし
- langの情報を取得してAtomで管理する
なし
> feat: 全てのlangを取得する機能

- package.json
- src/components/CodeArea/index.tsx
- yarn.lock
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/39
> コードエリアコンポーネント追加

- src/stores/searchWordsAtom.ts
Closes 
tag から post の id を取得して、その id から post の中身を取得して、 Post の型に変換する
tag から post の id を取得して、その id から post の中身を取得して、 Post の型に変換する
> feat: 任意のタグからポストを検索して取得する機能

- src/app/(use-header)/layout.tsx
- src/app/(use-header)/mypage/_components/view/Page/index.module.scss
- src/app/(use-header)/mypage/_components/view/Page/index.tsx
- src/app/_components/LoginProvider/index.tsx
- src/types/auth.ts
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/50
> feat: Add user ID to authentication data

- src/stores/userPostListAtom.ts
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/43
suapbase から特定のユーザの投稿を取得する
なし
```tsx
async function fetchUserPostList(userUid: string): Promise<Post[]> {...}
export const userPostListAtom = atom(async (get) => {
const auth = get(authAtom);
if (auth === undefined) {
return [];
}
return await fetchUserPostList(auth.uid);
});
```
なし
> feat: 特定ユーザのUUIDに紐づいて記事を取得する機能

- src/utils/upsertUser.ts
- supabase/migrations/20241029092513_set-user-table-uid-primary-key.sql
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/52
なし
nameとuidを受け取ってDBにupsertする
なし
> feat: ユーザーテーブルにユーザを追加する

- src/app/(use-header)/codes/_components/view/Page/index.module.scss
- src/app/(use-header)/codes/_components/view/Page/index.tsx
- src/app/(use-header)/codes/page.tsx
Closes [#41 ](https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/41)
> feat: 鑑賞する画面の完成

- src/app/(use-header)/post/_components/logic/useCrazyScore.tsx
Closes #48 
なし
評価のvalueが変わるカスタムフックの追加
> useCrazyScoreフックの追加

- src/stores/postListAtom.ts
- src/stores/searchWordsAtom.ts
- src/stores/userPostListAtom.ts
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/67
これまでは取得した全てのポストの平均を出していただけなので修正
取得した全てのポストの平均を出していた
特定のポストに対する平均のみを取得
> fix: 評価の平均を正しく取る

- src/app/(use-header)/mypage/_components/view/Page/index.tsx
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/46
> マイページのロジックを追加

- package.json
- src/shema/index.ts
- src/utils/ai.ts
- yarn.lock
Closes https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/57
AIでタイトルと説明を作る機能
なし
```ts
export async function askAIResponse(sourceCode: string, lang?: string): Promise<AIResponse | undefined> {
const model: GenerativeModel = await ai.getGenerativeModel({
model: 'gemini-1.5-flash',
generationConfig: {
responseMimeType: 'application/json',
},
});
const prompt = `
略
`
const response = await model.generateContent(prompt);
const text: string = response.response.text();
const res = zAIResponse.safeParse(JSON.parse(text));
if (res.success) {
return res.data;
}
return undefined;
}
```
なし
> feat: AIでタイトルと説明を作る機能

- src/app/(use-header)/mypage/_components/view/Page/index.module.scss
Closes [#65 ](https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/65)
project-exercises-kuso/src/app/(use-header)/mypage/_components/view/Page/index.module.scss
の中の＠media screen{}でwidthとpadding-topが効かない
> feat: 閲覧画面のcss一部変更

- src/app/(use-header)/codes/_components/view/Page/Card.module.scss
- src/app/(use-header)/codes/_components/view/Page/index.module.scss
- src/components/CodeArea/index.module.scss
- src/components/CodeArea/index.tsx
- userのiconのサイズを調整した
- ついでにコードブロック内のpaddingを修正した
Closes [#82 ](https://github.com/SystemEngineeringTeam/project-exercises-kuso/issues/82)
> fix: userのiconのサイズを調整した
